# Generated by Django 6.0.2 on 2026-03-18 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcecode',
            name='project',
        ),
        migrations.RemoveField(
            model_name='sourcecode',
            name='file_name',
        ),
        migrations.AddField(
            model_name='sourcecode',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source_codes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
